# Generated by Django 5.0.2 on 2024-03-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_remove_post_liked_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='post',
            new_name='post_id',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='liker',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='creator',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='postcontent',
            field=models.TextField(),
        ),
    ]
