# Generated by Django 5.0.2 on 2024-03-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_post_likes_post_id_rename_liker_likes_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likescount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='postcontent',
            field=models.TextField(default=''),
        ),
    ]
