# Generated by Django 5.0.2 on 2024-03-27 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_likes_post_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Followers',
        ),
    ]
